# generate_cod2_symbols.ps1
# Single script that, for each configured module:
#   1. Scans the Binary Ninja pseudo-C dump to find function start addresses + lengths
#   2. Emits a C++ header with a sorted symbol table and binary-search lookup helpers
#
# Re-run whenever any .bndb_pseudo_c.txt or .functions.txt file is updated.
# generate_mss32_symbols_h.ps1 remains separate because it is invoked by CMake post-build.

# ── Per-module configuration ──────────────────────────────────────────────────
$modules = @(
    @{
        # Binary Ninja pseudo-C dump of the whole binary
        BigFile    = "$PSScriptRoot\CoD2MP_s.exe.bndb_pseudo_c.txt"
        # List of function names to extract (one per line)
        NamesFile  = "$PSScriptRoot\CoD2MP_s.exe.bndb_pseudo_c.functions.txt"
        # Output C++ header
        OutHdr     = "$PSScriptRoot\..\mss32\symbols_cod2mp_s.h"
        # C++ identifiers
        Guard      = "SYMBOLS_COD2MP_S_H"
        StructName = "Cod2mpSymbol"
        Prefix     = "symbols_cod2mp_s"
        # Human-readable module description used in header comments
        ModuleDesc = "CoD2MP_s.exe"
    },
    @{
        BigFile    = "$PSScriptRoot\gfx_d3d_mp_x86_s.dll.bndb_pseudo_c.txt"
        NamesFile  = "$PSScriptRoot\gfx_d3d_mp_x86_s.dll.bndb_pseudo_c.functions.txt"
        OutHdr     = "$PSScriptRoot\..\mss32\symbols_gfx_d3d_mp_x86_s.h"
        Guard      = "SYMBOLS_GFX_D3D_MP_X86_S_H"
        StructName = "GfxD3dSymbol"
        Prefix     = "symbols_gfx_d3d_mp_x86_s"
        ModuleDesc = "gfx_d3d_mp_x86_s.dll"
    }
)

# ── Shared state-machine: parse one BN pseudo-C dump ─────────────────────────
# Returns a hashtable: functionName -> List of @{ AddrHex; AddrInt; Len }
function Get-FunctionLookup([string]$bigFile) {
    # Exactly 4 spaces = top-level function definition (not indented body lines)
    $defPattern   = '^([0-9a-fA-F]{8})    [^ ].* ([^ (]+)\(.*\)(\s+__\w+)*\s*$'
    # Exactly 2 spaces = function-level closing brace
    $closePattern = '^[0-9a-fA-F]{8}  \}\s*$'
    # Any line that starts with a hex address (used to find the end address)
    $anyAddr      = '^([0-9a-fA-F]{8})'

    $lookup      = @{}
    $currentAddr = -1L
    $currentName = $null
    $afterClose  = $false

    function Store-Func([string]$name, [long]$addrInt, [long]$len) {
        if (-not $lookup.ContainsKey($name)) {
            $lookup[$name] = [System.Collections.Generic.List[hashtable]]::new()
        }
        $lookup[$name].Add(@{
            AddrHex = '0x{0:x8}' -f $addrInt
            AddrInt = $addrInt
            Len     = $len      # -1 = unknown (no closing brace found)
        })
    }

    foreach ($line in [System.IO.File]::ReadLines($bigFile)) {
        # Step 1: if waiting for end-address, grab the first hex-addressed line
        if ($afterClose -and $line -match $anyAddr) {
            $endAddr = [Convert]::ToInt64($Matches[1], 16)
            Store-Func $currentName $currentAddr ($endAddr - $currentAddr)
            $afterClose  = $false
            $currentAddr = -1L
            $currentName = $null
            # Fall through: this line may itself be a new function definition
        }

        # Step 2: new function definition line
        if ($line -match $defPattern) {
            if ($currentAddr -ne -1L -and -not $afterClose) {
                Store-Func $currentName $currentAddr -1
            }
            $currentAddr = [Convert]::ToInt64($Matches[1], 16)
            $currentName = $Matches[2]
            $afterClose  = $false
        }
        # Step 3: closing brace line
        elseif ($currentAddr -ne -1L -and $line -match $closePattern) {
            $afterClose = $true
        }
    }
    # Flush last function if the file ended without a trailing address line
    if ($currentAddr -ne -1L) { Store-Func $currentName $currentAddr -1 }

    return $lookup
}

# ── Shared header emitter ─────────────────────────────────────────────────────
function Write-SymbolHeader([PSCustomObject[]]$entries, [hashtable]$mod) {
    $guard      = $mod.Guard
    $structName = $mod.StructName
    $prefix     = $mod.Prefix
    $moduleDesc = $mod.ModuleDesc
    $outHdr     = $mod.OutHdr

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("#ifndef $guard")
    $null = $sb.AppendLine("#define $guard")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("// Auto-generated by generate_cod2_symbols.ps1 - do not edit manually.")
    $null = $sb.AppendLine("// Maps $moduleDesc function start addresses + lengths to symbol names.")
    $null = $sb.AppendLine("// Use ${prefix}_getName(addr) to resolve any address inside a function.")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("#include <stdint.h>")
    $null = $sb.AppendLine("#include <stddef.h>")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("struct $structName")
    $null = $sb.AppendLine("{")
    $null = $sb.AppendLine("    uint32_t    addr;   // function start address")
    $null = $sb.AppendLine("    uint32_t    len;    // function length in bytes")
    $null = $sb.AppendLine("    const char* name;   // symbol name from Binary Ninja")
    $null = $sb.AppendLine("};")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("static const $structName ${prefix}[] =")
    $null = $sb.AppendLine("{")

    foreach ($e in $entries) {
        $line = "    { 0x" + ('{0:x8}' -f $e.Addr) + "u, 0x" + ('{0:x}' -f $e.Len) + "u, `"" + $e.Name + "`" },"
        $null = $sb.AppendLine($line)
    }

    $null = $sb.AppendLine("};")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("static const size_t ${prefix}_count = sizeof(${prefix}) / sizeof(${prefix}[0]);")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("// Returns the $structName entry whose range contains 'addr', or nullptr.")
    $null = $sb.AppendLine("static inline const ${structName}* ${prefix}_find(uint32_t addr)")
    $null = $sb.AppendLine("{")
    $null = $sb.AppendLine("    int lo = 0;")
    $null = $sb.AppendLine("    int hi = (int)${prefix}_count - 1;")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("    while (lo <= hi)")
    $null = $sb.AppendLine("    {")
    $null = $sb.AppendLine("        int mid = lo + (hi - lo) / 2;")
    $null = $sb.AppendLine("        const ${structName}& f = ${prefix}[mid];")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("        if (addr < f.addr)")
    $null = $sb.AppendLine("            hi = mid - 1;")
    $null = $sb.AppendLine("        else if (addr >= f.addr + f.len)")
    $null = $sb.AppendLine("            lo = mid + 1;")
    $null = $sb.AppendLine("        else")
    $null = $sb.AppendLine("            return &${prefix}[mid];")
    $null = $sb.AppendLine("    }")
    $null = $sb.AppendLine("    return nullptr;")
    $null = $sb.AppendLine("}")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("// Returns the symbol name if 'addr' falls within a known function's range,")
    $null = $sb.AppendLine("// or nullptr if not found.")
    $null = $sb.AppendLine("static inline const char* ${prefix}_getName(uint32_t addr)")
    $null = $sb.AppendLine("{")
    $null = $sb.AppendLine("    const ${structName}* f = ${prefix}_find(addr);")
    $null = $sb.AppendLine("    return f ? f->name : nullptr;")
    $null = $sb.AppendLine("}")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("#endif // $guard")

    [System.IO.File]::WriteAllText($outHdr, $sb.ToString(), [System.Text.Encoding]::UTF8)
    Write-Host "  -> Written: $outHdr" -ForegroundColor Green
}

# ── Main loop: process each module ───────────────────────────────────────────
foreach ($mod in $modules) {
    Write-Host ""
    Write-Host "=== $($mod.ModuleDesc) ===" -ForegroundColor Magenta

    # ── Phase 1: build address lookup from pseudo-C dump ─────────────────────
    Write-Host "Scanning: $($mod.BigFile)" -ForegroundColor Cyan
    $lookup = Get-FunctionLookup $mod.BigFile
    Write-Host "  -> $($lookup.Count) unique function definitions indexed" -ForegroundColor Gray

    # ── Phase 2: resolve wanted names ────────────────────────────────────────
    $wantedRaw = Get-Content $mod.NamesFile |
                 Where-Object { $_.Trim() -ne '' } |
                 Sort-Object -Unique

    Write-Host "Searching for $($wantedRaw.Count) names from: $($mod.NamesFile)" -ForegroundColor Cyan

    $found    = 0
    $notFound = 0

    $entries = @(foreach ($raw in $wantedRaw) {
        $name = ($raw -replace '\(.*', '').Trim()
        if ($name -eq '') { continue }

        if ($lookup.ContainsKey($name)) {
            $found++
            foreach ($entry in $lookup[$name]) {
                if ($entry.Len -ge 0) {
                    [PSCustomObject]@{
                        Addr = [uint32]$entry.AddrInt
                        Len  = [uint32]$entry.Len
                        Name = $name -replace '\\','\\' -replace '"','\"'
                    }
                }
            }
        } else {
            $notFound++
        }
    }) | Sort-Object Addr

    Write-Host "  -> $found found, $notFound not found" -ForegroundColor Yellow
    Write-Host "Generating header with $($entries.Count) entries" -ForegroundColor Cyan
    Write-SymbolHeader $entries $mod
}

Write-Host ""
Write-Host "All modules done." -ForegroundColor Green
